---
# Riemann

- name: Install deps
  apt: pkg={{ item }} state=present
  with_items: riemann_apt_dependencies

- file: path=/etc/sv/{{riemann_tools_cmd}}/log state=directory
- file: path=/etc/service state=directory
- file: path=/var/log/{{riemann_tools_cmd}} state=directory

- shell: pip install httplib2
- shell: gem install nokogiri -- --use-system-libraries --with-xml2-include=/usr/include/libxml2/
- gem: name=bundler state=present
- shell: gem install beefcake -v 1.0.0
- shell: gem install riemann-tools

- template: dest=/etc/sv/riemann-health/run mode=0755 src=riemann_health_run.sh
- template: dest=/etc/sv/riemann-health/log/run mode=0755 src=log_run

- file: src=/etc/sv/{{riemann_tools_cmd}}  dest=/etc/service/{{riemann_tools_cmd}} state=link
- runit: name={{riemann_tools_cmd}} state=started

